### ISSUE TITLE
panic in initTZ

### ISSUE THREAD

**Issue by dschub** [godror/godror#112]
**Describe the bug**
Updating from v0.17.5 to v0.20.9 results in a panic when trying to connect to the DB.

**Error output**
```golang
panic: 13:40:49:088595: 13:40:49:088595: strconv.ParseInt: parsing "40:49:088595": invalid syntax

goroutine 1 [running]:
github.com/godror/godror.(*conn).initTZ(0xc000396000, 0x0, 0x0)
	/home/x/go/lib/pkg/mod/github.com/godror/godror@v0.20.9/conn.go:529 +0x1c34
github.com/godror/godror.(*conn).init(0xc000396000, 0x0, 0x0, 0x0)
	/home/x/go/lib/pkg/mod/github.com/godror/godror@v0.20.9/conn.go:454 +0x205
github.com/godror/godror.(*drv).createConn(0x121c9e0, 0xc000534000, 0xc0000341e0, 0xc, 0xc000034207, 0x33, 0xc0000341ed, 0x19, 0x0, 0x0, ...)
	/home/x/go/lib/pkg/mod/github.com/godror/godror@v0.20.9/drv.go:307 +0x4a6
github.com/godror/godror.(*drv).createConnFromParams(0x121c9e0, 0xc0000341e0, 0xc, 0xc000034207, 0x33, 0xc0000341ed, 0x19, 0x0, 0x0, 0x0, ...)
	/home/x/go/lib/pkg/mod/github.com/godror/godror@v0.20.9/drv.go:500 +0x198
github.com/godror/godror.connector.Connect(0x121c9e0, 0xc0000341e0, 0xc, 0xc000034207, 0x33, 0xc0000341ed, 0x19, 0x0, 0x0, 0x0, ...)
	/home/x/go/lib/pkg/mod/github.com/godror/godror@v0.20.9/drv.go:979 +0x958
database/sql.(*DB).conn(0xc00007d110, 0xeb5060, 0xc0000280c8, 0xea6101, 0x0, 0x0, 0x0)
	/usr/lib64/golang/src/database/sql/sql.go:1294 +0xda4
database/sql.(*DB).PingContext(0xc00007d110, 0xeb5060, 0xc0000280c8, 0x0, 0x0)
	/usr/lib64/golang/src/database/sql/sql.go:799 +0xa6
database/sql.(*DB).Ping(0xc00007d110, 0x0, 0x0)
	/usr/lib64/golang/src/database/sql/sql.go:817 +0x55
```

**Your oracle version**
Server 12.2.0.1.0 with Instantclient 19.9

**Your godror version**
v0.20.9

**Your go version**
1.15.5

**Your gcc version**
9.3.0

**Machine:**
 - OS: Linux
 - Architecture: x86_64
 - Version: Solus

**Additional context**
The DB I'm trying to connect to has a non standard value set for `NLS_TIMESTAMP_TZ_FORMAT` that sadly does not include the timezone (`yyyy-mm-dd hh24:mi:ss:FF`), which is probably why the following code does not yield the intended result:
https://github.com/godror/godror/blob/2e9dcd7ba8b71794df717bfced818c61595c8c4e/conn.go#L485

A possible solution might be to only query the timezone in the first place, independent of what is set for `NLS_TIMESTAMP_TZ_FORMAT`:
```sql
SELECT DBTIMEZONE, TO_CHAR(SYSTIMESTAMP, 'TZR') FROM DUAL;
```

**Comment by tgulacsi** [comment]
Nice catch, thanks!
