### ISSUE TITLE
syscall, 140 minutes, locked to thread

### ISSUE THREAD

**Issue by volker-raschek** [godror/godror#173]
**Describe the bug**

In a production environment exits our container application. The readyness endpoint failed. The readyness endpoint calls three times the `sql.Ping()` method to verify if the database is still alive. But instead to check if the database is alive the binary exits with the following stack trace:

```text
goroutine 362201 [syscall, 140 minutes, locked to thread]:
github.com/godror/godror._Cfunc_dpiConn_create(0x7f9524068f80, 0x0, 0x0, 0x0, 0x0, 0x7f9470e0f580, 0x17, 0x0, 0xc00e2c4000, 0xc00c488a88, ...)
	_cgo_gotypes.go:2249 +0x4b
github.com/godror/godror.(*drv).acquireConn.func8.1(0xc0004d8b90, 0xc00e2f0190, 0x0, 0x0, 0xc00e2f0198, 0x0, 0x0, 0xc00e2f01a8, 0xc00e2f0500, 0x0, ...)
	/root/go/pkg/mod/github.com/godror/godror@v0.23.1/drv.go:509 +0x1a5
github.com/godror/godror.(*drv).acquireConn.func8(0x4288d8)
	/root/go/pkg/mod/github.com/godror/godror@v0.23.1/drv.go:509 +0x91
github.com/godror/godror.(*drv).checkExec(0xc0004d8b90, 0xc00e2f02d0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/godror/godror@v0.23.1/drv.go:217 +0x5a
github.com/godror/godror.(*drv).acquireConn(0xc0004d8b90, 0xc00017a000, 0xc000364249, 0x9, 0xc000612090, 0x17, 0xc000364253, 0x6, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/godror/godror@v0.23.1/drv.go:502 +0x731
github.com/godror/godror.(*drv).createConn(0xc0004d8b90, 0xc00017a000, 0xc000364249, 0x9, 0xc000612090, 0x17, 0xc000364253, 0x6, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/godror/godror@v0.23.1/drv.go:324 +0xd8
github.com/godror/godror.(*drv).createConnFromParams(0xc0004d8b90, 0xc000364249, 0x9, 0xc000612090, 0x17, 0xc000364253, 0x6, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/godror/godror@v0.23.1/drv.go:539 +0x158
github.com/godror/godror.connector.Connect(0xc0004d8b90, 0xc000364249, 0x9, 0xc000612090, 0x17, 0xc000364253, 0x6, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/godror/godror@v0.23.1/drv.go:1028 +0x51a
database/sql.(*DB).conn(0xc00062c1a0, 0x1929050, 0xc0000420a0, 0xc0002af601, 0x42edeb, 0x150, 0x1634ac0)
	/usr/lib/golang/src/database/sql/sql.go:1301 +0x184
database/sql.(*DB).PingContext(0xc00062c1a0, 0x1929050, 0xc0000420a0, 0xc, 0xc00e2dc348)
	/usr/lib/golang/src/database/sql/sql.go:799 +0x90
database/sql.(*DB).Ping(...)
	/usr/lib/golang/src/database/sql/sql.go:817
trrsuv040.agfahealthcare.com/orbis-u/ng-proxy/t1k/pkg/server.(*Handler).getReadyStatus(0xc00062e7e0, 0x19273b0, 0xc00e24a000, 0xc00da13f00)
	/workspace/pkg/server/handler.go:374 +0x1f5
net/http.HandlerFunc.ServeHTTP(0xc000439d60, 0x19273b0, 0xc00e24a000, 0xc00da13f00)
	/usr/lib/golang/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00048c000, 0x19273b0, 0xc00e24a000, 0xc00da13a00)
	/root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc0003782a0, 0x19273b0, 0xc00e24a000, 0xc00da13a00)
``` 
Here is an exerpt of the called method `getReadyStatus`. 

```go 
func (h *Handler) getReadyStatus(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/plain")

	if h.sqlDB != nil {
		n := 3
		for i := 1; i <= n; i++ {
			err := h.sqlDB.Ping()
			switch {
			case err != nil && i < n:
				h.logger.WithFields(logrus.Fields{
					"collector": metadata.ProxyCollector,
					"err":       err.Error(),
					"max-tries": n,
					"try":       i,
				}).Warn("unable to ping database - try next")
				continue
			case err != nil && i == n:
				h.logger.WithFields(logrus.Fields{
					"collector": metadata.ProxyCollector,
					"err":       err.Error(),
					"max-tries": n,
					"try":       i,
				}).Error("unable to ping database")
				http.Error(w, "not ready", http.StatusInternalServerError)
				return
			default:
				w.WriteHeader(http.StatusOK)
				fmt.Fprintf(w, "ready")
				return
			}
		}
	}
}
```

**To Reproduce**

Can not reproduce this bug. The error occured on a production environment.

**Expected behavior**

No returned error /  stacktrace

**Your oracle client version**

```bash
$ sqlplus64 --version
SQL*Plus: Release 12.2.0.1.0 Production
```

**Your godror version**

v0.23.1

**Your go version**

```bash
$ yum list installed | grep golang
golang.x86_64                               1.16-0.el7                 @golang  
golang-bin.x86_64                           1.16-0.el7                 @golang  
golang-src.noarch                           1.16-0.el7                 @golang
```

**Your gcc version**

```bash
$ yum list installed | grep gcc
gcc.x86_64                                  4.8.5-44.el7               @base    
gcc-c++.x86_64                              4.8.5-44.el7               @base    
gcc-gfortran.x86_64                         4.8.5-44.el7               @base    
libgcc.x86_64                               4.8.5-44.el7               @base 
```

**Machine (please complete the following information):**

 - OS: CentOS 7
 - Architecture:  x86_64
 - Version: [e.g. 10]

**Additional context**

I don't know exactly what godor is doing in the functions where the error was thrown, but for me as a layman who only uses the library, I don't rule out that maybe the database connection or the pool is broken as well.

**Comment by tgulacsi** [comment]
First of all, use PingContext with contrct.WithTimeout(r.Context(),time.Minute)).

Otherwise this will happen.
