### ISSUE TITLE
DPI-1002: invalid dpiObjectType handle error while using type with nested collection attribute 

### ISSUE THREAD

**Issue by sergej-klimenko** [godror/godror#180]
**Describe the bug**
During closing ObjectType of attribute, which is varray, got 
DPI-1002: invalid dpiObjectType handle from ODPI call dpiObjectType_release.
Besides, it seems that cause app to crash with segfault occasionally during 
ODPI calls if extensively used in goroutines.

**To Reproduce**
Minimal test.
```go
package main

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"log"

	"github.com/godror/godror"
)

func main() {
	godror.Log = godror.NewLogfmtLog(os.Stdout)

	eDSN := os.Getenv("GODROR_TEST_DSN")
	fmt.Printf("eDSN: %s\n", eDSN)

    ctx := context.Background()
	db, err := sql.Open("godror", eDSN)
	if err != nil {
	    log.Fatal(err.Error())
	}
	err = db.Ping()
	if err != nil {
	    log.Fatal(err.Error())
	}
	err = createTypes(ctx, db)
	if err != nil {
	    log.Fatal(err.Error())
	}
	err = getObjectType(ctx, db)
	if err != nil {
		log.Fatal(err.Error())
	}
}

func getObjectType(ctx context.Context, db *sql.DB) error {
	cx, err := db.Conn(ctx)
	if err != nil {
		return err
	}
    defer cx.Close()

	objType, err := godror.GetObjectType(ctx, cx, "TEST_TYPE")
	if err != nil {
		return err
	}
	defer objType.Close()
	
	return nil
}

func createTypes(ctx context.Context, db *sql.DB) error {
	qry := []string{
	`create or replace type test_list force as varray(30) of varchar2(30);`,
	`create or replace type test_type force as object (
   	  id    number(10),  
          list  test_list
        );`};
	for _, ddl := range qry {
		_, err := db.ExecContext(ctx, ddl)
		if err != nil {
			return err
		}
	}
	return nil
}
```

**Expected behavior**
No errors in ODPI output.

**Error output**
```
msg=PrepareContext shortcut=--GET_CONNECTION--
msg=GetObjectType name=TEST_TYPE
ODPI [22014647] 2021-09-14 16:01:27.145: fn start dpiConn_getObjectType(0x6a04b60)
ODPI [22014647] 2021-09-14 16:01:27.153: fn end dpiConn_getObjectType(0x6a04b60) -> 0
ODPI [22014647] 2021-09-14 16:01:27.153: fn start dpiObjectType_getInfo(0x3a90bb50)
ODPI [22014647] 2021-09-14 16:01:27.153: fn end dpiObjectType_getInfo(0x3a90bb50) -> 0
ODPI [22014647] 2021-09-14 16:01:27.153: fn start dpiObjectType_getAttributes(0x3a90bb50)
ODPI [22014647] 2021-09-14 16:01:27.160: fn end dpiObjectType_getAttributes(0x3a90bb50) -> 0
ODPI [22014647] 2021-09-14 16:01:27.160: fn start dpiObjectAttr_getInfo(0x3a90b790)
ODPI [22014647] 2021-09-14 16:01:27.160: fn end dpiObjectAttr_getInfo(0x3a90b790) -> 0
i=0 attrInfo="unsupported value type"
ODPI [22014647] 2021-09-14 16:01:27.161: fn start dpiObjectAttr_getInfo(0x3a90b7f0)
ODPI [22014647] 2021-09-14 16:01:27.161: fn end dpiObjectAttr_getInfo(0x3a90b7f0) -> 0
i=1 attrInfo="unsupported value type"
ODPI [22014647] 2021-09-14 16:01:27.161: fn start dpiObjectType_getInfo(0x6a04aa0)
ODPI [22014647] 2021-09-14 16:01:27.161: fn end dpiObjectType_getInfo(0x6a04aa0) -> 0
msg=ObjectAttribute.Close name=ID
ODPI [22014647] 2021-09-14 16:01:27.161: fn start dpiObjectAttr_release(0x3a90b790)
ODPI [22014647] 2021-09-14 16:01:27.161: fn end dpiObjectAttr_release(0x3a90b790) -> 0
msg=ObjectAttribute.Close name=LIST
ODPI [22014647] 2021-09-14 16:01:27.161: fn start dpiObjectAttr_release(0x3a90b7f0)
ODPI [22014647] 2021-09-14 16:01:27.161: fn end dpiObjectAttr_release(0x3a90b7f0) -> 0
msg=ObjectType.Close name=TEST_LIST
ODPI [22014647] 2021-09-14 16:01:27.161: fn start dpiObjectType_release(0x6a04aa0)
ODPI [22014647] 2021-09-14 16:01:27.161: internal error DPI-1002: invalid dpiObjectType handle (dpiObjectType_release / check main handle)
ODPI [22014647] 2021-09-14 16:01:27.161: fn end dpiObjectType_release(0x6a04aa0) -> -1
msg="ObjectType.Close attr.Close" name=TEST_TYPE attr=LIST error="error on close object type: ORA-00000: DPI-1002: invalid dpiObjectType handle"
msg=ObjectType.Close name=TEST_TYPE
ODPI [22014647] 2021-09-14 16:01:27.161: fn start dpiObjectType_release(0x3a90bb50)
ODPI [22014647] 2021-09-14 16:01:27.161: fn end dpiObjectType_release(0x3a90bb50) -> 0
msg=IsValid connOK=true released=false pooled=true tzOK=true
ODPI [22014647] 2021-09-14 16:01:27.161: fn start dpiConn_release(0x6a04b60)
ODPI [22014647] 2021-09-14 16:01:27.161: fn end dpiConn_release(0x6a04b60) -> 0
```
**Your oracle client version**
19.8.0.0.0

**Your godror version**
HEAD on main 

**Your go version**
1.16

**Your gcc version**
4.2.1

**Machine (please complete the following information):**
 - OS: MacOS
 - Architecture: x86_64
 - Version: 11.2.1

**Additional context**
Looks like we need to add ref to ObjectAttribute.ObjectType.dpiObjectType, similarly with t.CollectionOf.dpiObjectType, something like that
```go
func (t *ObjectType) init() error {
    // Skipped...
   
   for i, attr := range attrs {
      // Skipped ...
      objAttr := ObjectAttribute{
			  dpiObjectAttr: attr,
			  Name:          C.GoStringN(attrInfo.name, C.int(attrInfo.nameLength)),
			  ObjectType:    sub,
		  }
      if sub.dpiObjectType != nil {
	     C.dpiObjectType_addRef(sub.dpiObjectType)   // <-- similarly with t.CollectionOf.dpiObjectType above
      }
      //fmt.Printf("%d=%q. typ=%+v sub=%+v\n", i, objAttr.Name, typ, sub)
     t.Attributes[objAttr.Name] = objAttr
   }
   
   // Skipped ...
   return nil
}

**Comment by tgulacsi** [comment]
Thanks for the report!

ATM I cannot reproduce it - please take a look at https://github.com/godror/godror/blob/f64714928c4e281455b2011e19ac6fe268d9a534/z_plsql_types_test.go#L1094 and help what does differ from your case!

Surely we can add that reference to the sub-object type, but I don't know who and where will decrement it, so I'd like some help from @sudarshan12s on this.

**Comment by sergej-klimenko** [comment]
Without that reference increment in 41350750930adfedd8951f5bcac43050ae3229c7 i still see those DPI errors with DPI_DEBUG_LEVEL=92
after running TestSubObjectTypeClose on each run
```
ODPI [22076275] 2021-09-14 22:01:06.821: fn start dpiObjectType_release(0xce0a000)
ODPI [22076275] 2021-09-14 22:01:06.821: internal error DPI-1002: invalid dpiObjectType handle (dpiObjectType_release / check main handle)
```
And if repeat that test a sufficiently large number of times (go test -v -run  TestSubObjectTypeClose -count 100, for example), it hangs with segfault, sooner or later
```
=== RUN   TestSubObjectTypeClose
    z_plsql_types_test.go:1141: Run 0 group
    z_plsql_types_test.go:1141: Run 1 group
    z_plsql_types_test.go:1141: Run 2 group
    z_plsql_types_test.go:1141: Run 3 group
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x306c9718]

runtime stack:
runtime.throw(0x43e9101, 0x2a)
	/usr/local/Cellar/go/1.16.6/libexec/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/Cellar/go/1.16.6/libexec/src/runtime/signal_unix.go:718 +0x2ef

goroutine 2579 [syscall, locked to thread]:
runtime.cgocall(0x433fcd0, 0xc000145b10, 0xc000348900)
	/usr/local/Cellar/go/1.16.6/libexec/src/runtime/cgocall.go:154 +0x5b fp=0xc000145ae0 sp=0xc000145aa8 pc=0x400503b
github.com/godror/godror._Cfunc_dpiObjectType_getAttributes(0xc30d610, 0xc000340002, 0xc000348900, 0xc000000000)
	_cgo_gotypes.go:3798 +0x48 fp=0xc000145b10 sp=0xc000145ae0 pc=0x41ba6e8
github.com/godror/godror.(*ObjectType).init.func3(0xc30d610, 0xc000145c08, 0x2)
	/Users/sergej/projects/golang/src/github.com/godror/godror/obj.go:579 +0xd0 fp=0xc000145b50 sp=0xc000145b10 pc=0x4205cd0
github.com/godror/godror.(*ObjectType).init(0xc000646100, 0x0, 0x0)
	/Users/sergej/projects/golang/src/github.com/godror/godror/obj.go:579 +0x3b1 fp=0xc000145ce0 sp=0xc000145b50 pc=0x41daf91
github.com/godror/godror.(*conn).GetObjectType(0xc0007765a0, 0xc000258048, 0x14, 0x0, 0x0, 0x0)
	/Users/sergej/projects/golang/src/github.com/godror/godror/obj.go:445 +0x5b7 fp=0xc000145e30 sp=0xc000145ce0 pc=0x41d9ab7
github.com/godror/godror.GetObjectType(0x44511d8, 0xc000707280, 0x4448b78, 0xc0004860f0, 0x43e0193, 0x14, 0x0, 0x1, 0x0)
	/Users/sergej/projects/golang/src/github.com/godror/godror/obj.go:666 +0x166 fp=0xc000145ea8 sp=0xc000145e30 pc=0x41dbd06
github.com/godror/godror_test.TestSubObjectTypeClose.func2(0x44511d8, 0xc000707280, 0xc00010b110, 0x0, 0x0)
	/Users/sergej/projects/golang/src/github.com/godror/godror/z_plsql_types_test.go:1130 +0xe5 fp=0xc000145f28 sp=0xc000145ea8 pc=0x42f0c45
github.com/godror/godror_test.TestSubObjectTypeClose.func3(0x0, 0x0)
	/Users/sergej/projects/golang/src/github.com/godror/godror/z_plsql_types_test.go:1148 +0x6e fp=0xc000145f78 sp=0xc000145f28 pc=0x42f0d8e
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0002c84b0, 0xc0002c8690)
```
I don’t know either where that added reference will be decremented, but that clearly helps and test keep running without segfault in loop.

**Comment by sergej-klimenko** [comment]
I think that ref will be decremented when closing subtype as attribute in ObjectAttribute.Close
https://github.com/godror/godror/blob/41350750930adfedd8951f5bcac43050ae3229c7/obj.go#L657

**Comment by tgulacsi** [comment]
Agreed, thanks (4135075 contains the modification).
