### ISSUE TITLE
Segfault when using ExecContext

### ISSUE THREAD

**Issue by rohithv-tw** [godror/godror#214]
**Describe the bug**
Segmentation Fault when godror is closing connection to database after executing the query

**To Reproduce**
```
type SampleStruct struct {
	FieldA  string       `db:"FIELD_A"`
	FieldB  string       `db:"FIELD_B"`
	FieldC string       `db:"FIELD_C"`
	FieldD int          `db:"FIELD_D"`
	FieldE  string       `db:"FIELD_E"`
	FieldF  sql.NullTime `db:"FIELD_F"`
	FieldG  sql.NullTime `db:"FIELD_G"`
}

db, _ := sql.Open("godror", `user="SYSTEM" password="password" connectString="localhost:1521/XE"`)

func CreateRecord(ctx context.Context, request SampleStruct) error {
	query := `INSERT INTO table_name(
		field_a,
		field_b,
		field_c,
		field_d,
		field_e) VALUES (:1,:2,:3,:4,:5)`
	_, err := db.ExecContext(ctx, query, request.FieldA, request.FieldB, request.FieldC, request.FieldD, request.FieldE)
	if err != nil {
		return err
	}
	return nil
}
```

**Expected behavior**
No Panic while query is executed using godror

**Error output**
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xcbc pc=0x7f9197d8bd31]

runtime stack:
runtime.throw(0xfba8a5, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:679 +0x46a

goroutine 42226 [syscall]:
runtime.cgocall(0xd27360, 0xc0004b65d8, 0x0)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0004b65a8 sp=0xc0004b6570 pc=0x40f9fb
github.com/godror/godror._Cfunc_dpiConn_release(0x2b73440, 0x0)
	_cgo_gotypes.go:2431 +0x49 fp=0xc0004b65d8 sp=0xc0004b65a8 pc=0xb07bf9
github.com/godror/godror.(*conn).closeNotLocking.func1(0x2b73440, 0xc0004b6660)
	/sample-api/vendor/github.com/godror/godror/conn.go:224 +0x4d fp=0xc0004b6608 sp=0xc0004b65d8 pc=0xb4491d
github.com/godror/godror.(*conn).closeNotLocking(0xc0011b6e00, 0x300000002, 0xc0004b66d8)
	/sample-api/vendor/github.com/godror/godror/conn.go:224 +0xa9 fp=0xc0004b6628 sp=0xc0004b6608 pc=0xb0d599
github.com/godror/godror.(*conn).Close(0xc0011b6e00, 0x0, 0x0)
	/sample-api/vendor/github.com/godror/godror/conn.go:203 +0x7e fp=0xc0004b6670 sp=0xc0004b6628 pc=0xb0d48e
database/sql.(*driverConn).finalClose.func2()
	/usr/local/go/src/database/sql/sql.go:573 +0x49 fp=0xc0004b66d0 sp=0xc0004b6698 pc=0xa128a9
database/sql.withLock(0x11257a0, 0xc001d7a280, 0xc0004b6758)
	/usr/local/go/src/database/sql/sql.go:3184 +0x69 fp=0xc0004b6700 sp=0xc0004b66d0 pc=0xa12519
database/sql.(*driverConn).finalClose(0xc001d7a280, 0xf078a0, 0x7f919a8efa48)
	/usr/local/go/src/database/sql/sql.go:571 +0x130 fp=0xc0004b6798 sp=0xc0004b6700 pc=0xa04d90
database/sql.finalCloser.finalClose-fm(0xc0005e0480, 0x1119ca0)
	/usr/local/go/src/database/sql/sql.go:617 +0x2f fp=0xc0004b67c0 sp=0xc0004b6798 pc=0xa14b7f
database/sql.(*driverConn).Close(0xc001d7a280, 0xc001d7a280, 0x0)
	/usr/local/go/src/database/sql/sql.go:552 +0x12b fp=0xc0004b6810 sp=0xc0004b67c0 pc=0xa04bbb
database/sql.(*DB).putConn(0xc0005e0480, 0xc001d7a280, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1329 +0x202 fp=0xc0004b6880 sp=0xc0004b6810 pc=0xa08af2
database/sql.(*driverConn).releaseConn(...)
	/usr/local/go/src/database/sql/sql.go:473
database/sql.(*driverConn).releaseConn-fm(0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:472 +0x4b fp=0xc0004b68b8 sp=0xc0004b6880 pc=0xa14bfb
database/sql.(*DB).execDC.func1(0xc0004b6b48, 0xc0004b6b38)
	/usr/local/go/src/database/sql/sql.go:1504 +0x3c fp=0xc0004b68d8 sp=0xc0004b68b8 pc=0xa12b6c
database/sql.(*DB).execDC(0xc0005e0480, 0x11365e0, 0xc00034a420, 0xc001d7a280, 0xc0004b6b48, 0xfd2c65, 0x83, 0xc0004b6c98, 0x5, 0x5, ...)
	/usr/local/go/src/database/sql/sql.go:1538 +0x36c fp=0xc0004b6ad8 sp=0xc0004b68d8 pc=0xa0a04c
database/sql.(*DB).exec(0xc0005e0480, 0x11365e0, 0xc00034a420, 0xfd2c65, 0x83, 0xc0004b6c98, 0x5, 0x5, 0x1, 0x1b, ...)
	/usr/local/go/src/database/sql/sql.go:1499 +0x139 fp=0xc0004b6b68 sp=0xc0004b6ad8 pc=0xa09c89
database/sql.(*DB).ExecContext(0xc0005e0480, 0x11365e0, 0xc00034a420, 0xfd2c65, 0x83, 0xc0004b6c98, 0x5, 0x5, 0x1, 0xc0004b6ce8, ...)
	/usr/local/go/src/database/sql/sql.go:1477 +0xde fp=0xc0004b6c08 sp=0xc0004b6b68 pc=0xa0989e
/sample-api/repository.sampleRepository.Create(0xc00019b7d0, 0xc001f004b0, 0xc0013e45d0, 0x24, 0xf942e0, 0x3, 0xf93958, 0x0, 0x0, 0xf9b40a, ...)
	/sample-api/repository/sample_repository.go:37 +0x20e fp=0xc0004b6cf8 sp=0xc0004b6c08 pc=0xcf994e
```

**Your oracle client version**
12.2.0.1.0

**Your oracle server version**
19

**Your godror version**
v0.26.0

**Your go version**
1.13

**Your gcc version**
e.g. 4.8.3

**Machine (please complete the following information):**
 - OS: linux (Docker image - Golang alpine image)
 - Architecture: [e.g. x64]

**Additional context**
Same stack trace as mentioned at https://github.com/godror/godror/issues/100. Issue is still reproducible even in newer versions

**Comment by tgulacsi** [comment]
Is it reproducible with the latest stable (v0.30.2) or @master?
How? #100 is about connection problems during execution. Is it the same here?
What if you PrepareContext + ExecContext + Stmt.Close?

And please provide a runnable test, best by expandint `z_test.go`.
(Your example here have several problems: no error handling, mismatched struct fields definition and use...)
