### ISSUE TITLE
 oracle.xdb.XMLType class not found exception

### ISSUE THREAD

**Issue by neeraj-clumio** [godror/godror#271]
**Describe the bug**
EMR Sqoop Job failed with an error oracle.xdb.XMLType class not found exception 

**To Reproduce**
Appears to be happening with a specific database during querying the tables in a sqoop job.

**Expected behavior**
Query should be successfull.

**Error output**
java.lang.ClassNotFoundException: oracle.xdb.XMLType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at oracle.jdbc.driver.NamedTypeAccessor.getString(NamedTypeAccessor.java:351)
	at oracle.jdbc.driver.GeneratedStatement.getString(GeneratedStatement.java:289)
	at oracle.jdbc.driver.GeneratedScrollableResultSet.getString(GeneratedScrollableResultSet.java:376)
	at org.apache.sqoop.lib.JdbcWritableBridge.readString(JdbcWritableBridge.java:71)
	at com.cloudera.sqoop.lib.JdbcWritableBridge.readString(JdbcWritableBridge.java:61)
	at QueryResult.readFields(QueryResult.java:410)
	at org.apache.sqoop.mapreduce.db.DBRecordReader.nextKeyValue(DBRecordReader.java:244)
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:565)
	at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145)
	at org.apache.sqoop.mapreduce.AutoProgressMapper.run(AutoProgressMapper.java:64)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:796)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:342)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:169)

**Your oracle client version**
 "engine": "oracle-se2"
   "engineVersion": "19.0.0.0.ru-2022-10.rur-2022-10.r1"

**Your godror version**
v0.34.0

**Your go version**
go1.19.1

**Your gcc version**
e.g. 4.8.3

**Machine (please complete the following information):**
os.name: Linux
os.version: 4.14.173-137.229.amzn2.x86_64
java.home: /usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64/jre
java.runtime.version: 1.8.0_352-b08
java.vendor: Amazon.com Inc.
java.version: 1.8.0_352
java.vm.name: OpenJDK 64-Bit Server VM

**Additional context**

**Comment by tgulacsi** [comment]
1. This is a specific DB's problem: either permission or XDB is not installed.
2. 2. This is  a Go driver, not java
