### ISSUE TITLE
The program crashes when executing the function

### ISSUE THREAD

**Issue by ad983** [godror/godror#289]
**Describe the bug**

Hello, when I use select from dual to call a custom function, a driver error occurs

The function creation statement is as follows:

```
CREATE OR REPLACE FUNCTION split_string2 (v_string IN VARCHAR2, v_delimiter IN VARCHAR2)
RETURN SYS.ODCIVARCHAR2LIST PIPELINED IS
  v_start_pos       PLS_INTEGER := 1;
  v_next_pos        PLS_INTEGER;
BEGIN
  LOOP
    v_next_pos := INSTR(v_string, v_delimiter, v_start_pos);
    IF v_next_pos = 0 THEN
      PIPE ROW (SUBSTR(v_string, v_start_pos));
      EXIT;
    END IF;
    PIPE ROW (SUBSTR(v_string, v_start_pos, v_next_pos - v_start_pos));
    v_start_pos := v_next_pos + LENGTH(v_delimiter);
  END LOOP;
  RETURN;
END;
```
go code:

```
package main

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/godror/godror"
	//_ "github.com/godror/godror"
	"time"
)

func main() {
	db, err := connectORACLE("172.19.33.115", "helowin", "xxx", "xxxx123123", 1522)
	if err != nil {
		panic(err)
	}

	defer db.Close()

	ctx := context.Background()

	_, err = db.ExecContext(ctx, fmt.Sprintf(`ALTER SESSION SET CURRENT_SCHEMA="%s"`, "TEST"))
	if err != nil {
		fmt.Println("err1:", err.Error())
		return
	}

	sql := `select split_string2('sdfasdf,asdfasdf',',') from dual`

	rows, err := db.QueryContext(ctx, sql)
	if err != nil {
		fmt.Println("err2:", err.Error())
		return
	}
	defer rows.Close()

	for rows.Next() {
		var text string
		err = rows.Scan(&text)
		if err != nil {
			panic(err.Error())
		}
		fmt.Printf("text: %s\n", text)
	}

}

func connectORACLE(host, serviceName, user, password string, port int) (*sql.DB, error) {

	var P godror.ConnectionParams
	var pp godror.PoolParams
	var cp godror.ConnParams

	pp.SessionTimeout = 30

	P.ConnectString = fmt.Sprintf(`(DESCRIPTION=(connect_timeout=5)(ADDRESS=(PROTOCOL=TCP)(HOST=%v)(PORT=%v))(CONNECT_DATA=(SID=%v)))`, host, port, serviceName)
	P.Username = user
	P.Password = godror.NewPassword(password)
	P.Timezone = time.Local
	P.StandaloneConnection = true
	P.PoolParams = pp
	P.ConnParams = cp
	dd := sql.OpenDB(godror.NewConnector(P))
	dd.SetMaxIdleConns(0)
	dd.SetMaxOpenConns(5)

	return dd, nil
}

```
   

**To Reproduce**
At least the offending source code;
the best is a minimal test case that reproduces the error.

**Expected behavior**

**Error output**
Copy the error output (panic, stack trace),
or the output of running with `DPI_DEBUG_LEVEL=92`.
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x679add]

runtime stack:
runtime.throw({0x725c59?, 0x6817ae?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7fff33d9bc60 sp=0x7fff33d9bc30 pc=0x44373d
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:819 +0x369 fp=0x7fff33d9bcb0 sp=0x7fff33d9bc60 pc=0x459269

goroutine 1 [syscall]:
runtime.cgocall(0x66804d, 0xc00010f8c8)
	/usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0xc00010f8a0 sp=0xc00010f868 pc=0x4119bc
github.com/godror/godror._Cfunc_dpiConn_release(0x1ffd090)
	_cgo_gotypes.go:2744 +0x48 fp=0xc00010f8c8 sp=0xc00010f8a0 pc=0x5fbcc8
github.com/godror/godror.(*conn).closeNotLocking.func1(0xc00010f988?)
	/opt/golang/pkg/mod/github.com/godror/godror@v0.37.0/conn.go:264 +0x3a fp=0xc00010f900 sp=0xc00010f8c8 pc=0x6043ba
github.com/godror/godror.(*conn).closeNotLocking(0xc000102400)
	/opt/golang/pkg/mod/github.com/godror/godror@v0.37.0/conn.go:264 +0x1dc fp=0xc00010f9f8 sp=0xc00010f900 pc=0x60433c
github.com/godror/godror.(*conn).Close(0xc000102400)
	/opt/golang/pkg/mod/github.com/godror/godror@v0.37.0/conn.go:239 +0x85 fp=0xc00010fa48 sp=0xc00010f9f8 pc=0x604085
database/sql.(*driverConn).finalClose.func2()
	/usr/local/go/src/database/sql/sql.go:645 +0x3c fp=0xc00010fa70 sp=0xc00010fa48 pc=0x4ebbbc
database/sql.withLock({0x77a0d0, 0xc0000fe240}, 0xc00010fb18)
	/usr/local/go/src/database/sql/sql.go:3439 +0x8c fp=0xc00010fab0 sp=0xc00010fa70 pc=0x4f9f6c
database/sql.(*driverConn).finalClose(0xc0000fe240)
	/usr/local/go/src/database/sql/sql.go:643 +0x116 fp=0xc00010fb58 sp=0xc00010fab0 pc=0x4eba76
database/sql.finalCloser.finalClose-fm()
	<autogenerated>:1 +0x2b fp=0xc00010fb70 sp=0xc00010fb58 pc=0x4fab0b
database/sql.(*driverConn).Close(0xc0000fe240)
	/usr/local/go/src/database/sql/sql.go:624 +0x13f fp=0xc00010fbb8 sp=0xc00010fb70 pc=0x4eb93f
database/sql.(*DB).putConn(0xc00009e5b0, 0xc0000fe240, {0x0, 0x0}, 0x0?)
	/usr/local/go/src/database/sql/sql.go:1490 +0x2e5 fp=0xc00010fc28 sp=0xc00010fbb8 pc=0x4ef9a5
database/sql.(*driverConn).releaseConn(0x77a0d0?, {0x0?, 0x0?})
	/usr/local/go/src/database/sql/sql.go:528 +0x37 fp=0xc00010fc60 sp=0xc00010fc28 pc=0x4eae37
database/sql.(*driverConn).releaseConn-fm({0x0?, 0x0?})
	<autogenerated>:1 +0x39 fp=0xc00010fc88 sp=0xc00010fc60 pc=0x4fab79
database/sql.(*Rows).close(0xc000100100, {0x0, 0x0})
	/usr/local/go/src/database/sql/sql.go:3333 +0x1e2 fp=0xc00010fd18 sp=0xc00010fc88 pc=0x4f9602
database/sql.(*Rows).Close(0x3?)
	/usr/local/go/src/database/sql/sql.go:3304 +0x1d fp=0xc00010fd40 sp=0xc00010fd18 pc=0x4f93fd
main.main.func2()
	/root/oracle-test/main.go:35 +0x26 fp=0xc00010fd58 sp=0xc00010fd40 pc=0x667806
runtime.deferCallSave(0xc00010fe28, 0xc00010fef0?)
	/usr/local/go/src/runtime/panic.go:796 +0x88 fp=0xc00010fd68 sp=0xc00010fd58 pc=0x442ee8
runtime.runOpenDeferFrame(0x4f7a2f?, 0xc00008a320)
	/usr/local/go/src/runtime/panic.go:769 +0x1a5 fp=0xc00010fdb0 sp=0xc00010fd68 pc=0x442d05
panic({0x6c2360, 0xc000083060})
	/usr/local/go/src/runtime/panic.go:884 +0x212 fp=0xc00010fe70 sp=0xc00010fdb0 pc=0x443152
main.main()
	/root/oracle-test/main.go:41 +0x3fc fp=0xc00010ff80 sp=0xc00010fe70 pc=0x66779c
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc00010ffe0 sp=0xc00010ff80 pc=0x445f92
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00010ffe8 sp=0xc00010ffe0 pc=0x473121

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000040fb0 sp=0xc000040f90 pc=0x446356
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:302 +0xad fp=0xc000040fe0 sp=0xc000040fb0 pc=0x4461ed
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000040fe8 sp=0xc000040fe0 pc=0x473121
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:290 +0x25

goroutine 18 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00003c790 sp=0xc00003c770 pc=0x446356
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00003c7c8 sp=0xc00003c790 pc=0x432a6e
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00003c7e0 sp=0xc00003c7c8 pc=0x427726
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00003c7e8 sp=0xc00003c7e0 pc=0x473121
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 19 [GC scavenge wait]:
runtime.gopark(0xc000080000?, 0x7777a0?, 0x1?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc00003cf70 sp=0xc00003cf50 pc=0x446356
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0xb3ebc0)
	/usr/local/go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc00003cfa0 sp=0xc00003cf70 pc=0x430b13
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc00003cfc8 sp=0xc00003cfa0 pc=0x4310e5
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc00003cfe0 sp=0xc00003cfc8 pc=0x4276c6
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00003cfe8 sp=0xc00003cfe0 pc=0x473121
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 20 [finalizer wait]:
runtime.gopark(0xb3efc0?, 0xc0000844e0?, 0x0?, 0x0?, 0xc000040770?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000040628 sp=0xc000040608 pc=0x446356
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:369
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:180 +0x10f fp=0xc0000407e0 sp=0xc000040628 pc=0x42682f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x473121
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:157 +0x45

goroutine 21 [select]:
runtime.gopark(0xc00003d788?, 0x2?, 0x11?, 0x0?, 0xc00003d784?)
	/usr/local/go/src/runtime/proc.go:363 +0xd6 fp=0xc000053e10 sp=0xc000053df0 pc=0x446356
runtime.selectgo(0xc000053f88, 0xc00003d780, 0x0?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:328 +0x7bc fp=0xc000053f50 sp=0xc000053e10 pc=0x4557bc
database/sql.(*DB).connectionOpener(0xc00009e5b0, {0x77a8a0, 0xc000086380})
	/usr/local/go/src/database/sql/sql.go:1224 +0x8d fp=0xc000053fb8 sp=0xc000053f50 pc=0x4ee22d
database/sql.OpenDB.func1()
	/usr/local/go/src/database/sql/sql.go:792 +0x2e fp=0xc000053fe0 sp=0xc000053fb8 pc=0x4ec84e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000053fe8 sp=0xc000053fe0 pc=0x473121
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:792 +0x18d
exit status 2
```

**Your oracle client version**
12.1

**Your godror version**
v0.37.0

**Your go version**
go version go1.19.4 linux/amd64

**Your gcc version**
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Machine (please complete the following information):**
Centos7.6

**Additional context**

**Comment by tgulacsi** [comment]
sql := `select * from TABLE(split_string2('sdfasdf,asdfasdf',','))`

**Comment by ad983** [comment]
> sql := `select * from TABLE(split_string2('sdfasdf,asdfasdf',','))`

root@jumpserver oracle-test]# go run main.go
text: sdfasdf
text: asdfasdf

@tgulacsi  Hi, This execution is successful
Have you found the cause of the abnormal crash?

**Comment by ad983** [comment]
@tgulacsi 
hi, hello, you can test this sql in plsql or navicat ,The results can be returned normally in the client.

`	
select split_string2('sdfasdf,asdfasdf',',') from dual
`

I guess it may be because of the problem of driver processing that caused panics，Suppose my call is not legal and should not return error instead of panics

**Comment by ad983** [comment]
@tgulacsi  hello, i tested the fix and there are still some bugs
	
`
select split_string2('sdfasdf,asd,fasdf',',') from dual 

` 
Navicat client returns results：
"SYS"."ODCIVARCHAR2LIST"('sdfasdf','asd','fasdf')

Godror  returns results：
{"CollectionOf":{"CollectionOf":null,"Attributes":null,"Schema":"SYS","Name":"ODCIVARCHAR2LIST","DBSize":4000,"ClientSizeInBytes":16000,"CharSize":4000,"OracleTypeNum":2001,"NativeTypeNum":3004,"Precision":0,"Scale":0,"FsPrecision":0},"Attributes":{},"Schema":"SYS","Name":"ODCIVARCHAR2LIST","DBSize":0,"ClientSizeInBytes":0,"CharSize":0,"OracleTypeNum":0,"NativeTypeNum":0,"Precision":0,"Scale":0,"FsPrecision":0}

**Comment by ad983** [comment]
@tgulacsi Got it, thanks

**Comment by ad983** [comment]
@tgulacsi  Hello, in fact, we are also working on a client application similar to plsql, which is a web-based B/S architecture that can support most databases such as Oracle, MySQL, DB2, MongoDB, etc., which is why I stand on the database I have dealt with this problem from the perspective of the client. What I value is not how to solve it

select split_string2('sdfasdf,asd,fasdf',',') from dual

This query returns the correct result, but cares whether it can return the same result as other clients such as plsql.

**Comment by ad983** [comment]
To add, this bug is like a time bomb in my opinion, we can bypass it, but you don't know when it will be triggered.
