### ISSUE TITLE
SIGSEGV in QueryContext

### ISSUE THREAD

**Issue by davidwartell** [godror/godror#299]
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7f77164abc50 pc=0x7f77351a07e0]
runtime stack:
runtime.throw({0xc2d3cb, 0x7f77373528f0})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x389
goroutine 424189 [syscall]:
runtime.cgocall(0xab2ad0, 0xc000689ed0)
	/usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc000689ea8 sp=0xc000689e70 pc=0x40fc3c
github.com/godror/godror._Cfunc_dpiStmt_execute(0x7f76fc197a40, 0x20, 0xc000ec8ac8)
	_cgo_gotypes.go:4173 +0x4c fp=0xc000689ed0 sp=0xc000689ea8 pc=0x790d6c
github.com/godror/godror.(*statement).QueryContext.func2.1(0xc000d72390, 0xd69fe0, 0xc000d72390)
	/src/vendor/github.com/godror/godror/stmt.go:555 +0x5c fp=0xc000689f18 sp=0xc000689ed0 pc=0x7b5dbc
github.com/godror/godror.(*statement).QueryContext.func2()
	/src/vendor/github.com/godror/godror/stmt.go:555 +0x12f fp=0xc000689fe0 sp=0xc000689f18 pc=0x7b5b4f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000689fe8 sp=0xc000689fe0 pc=0x470e41
created by github.com/godror/godror.(*statement).QueryContext
	/src/vendor/github.com/godror/godror/stmt.go:546 +0x73d

**To Reproduce**
QueryContext

**Expected behavior**
Not segfault

**Error output**
Copy the error output (panic, stack trace),
or the output of running with `DPI_DEBUG_LEVEL=92`.

**Your oracle client version**
e.g. release=19 update=13

**Your godror version**
e.g. v0.13.2 

**Your go version**
e.g. 1.17.0

**Your gcc version**
e.g. TBD

**Machine (please complete the following information):**
 - OS: oraclelinux:7-slim
 - Architecture: x86_64
 - Version: 

**Additional context**

**Comment by tgulacsi** [comment]
Please give us some clues: the query and the args you've given to QueryContext!

**Comment by skriap** [comment]
An example of the request:
`with pcc as
	(select pp.PIN, pp.CLASS, pp.CTLNUM
	from debit.partitioned_pintab pp
	where
	pp.CTLNUM = 1122334455)
    SELECT /*+ ORDERED */ 
		   ct.class, 
		   ct.currency_code, 
		   ct.divisor,
		   ct.service_type,
		   ct.rechg_threshold,
		   pin.pin, 
		   pin.ctlnum, 
		   pin.class, 
		   pin.pin_state, 
		   pin.balance, 
		   pin.fractional_cent,
		   sub.last_name,
		   sub.first_name, 
		   sub.email_address, 
		   sub.subscriber_plan_restricted, 
		   sub.univ_app_act_date,
		   sub.rechg_threshold, 
		   sub.rechg_amount,
		   plan.class_id, 
		   plan.ratetab, 
		   plan.plan_id, 
		   plan.name, 
		   plan.units, 
		   plan.type,
		   plan.high_usage_plan,
           plan.num_of_dest,
		   plan.subscriber_plan_expired_utc, 
		   plan.auto_renew, 
		   plan.status, 
		   plan.transaction_id,
		   topup.timestamp,
		   credit.CCARD_NUMBER,
		   credit.CCARD_TYPE,
		   credit.NAME_ON_CCARD,
		   credit.CCARD_EXP_DATE,
		   credit.CCARD_ADDRESS1,
		   credit.CCARD_ADDRESS2,
		   credit.CCARD_CITY,
		   credit.CCARD_STATE,
		   credit.CCARD_ZIP,
		   credit.CCARD_COUNTRY,
		   credit.ALLOW_MULTI_USE,
		   credit.CCARD_VAULT_HANDLE,
		   credit.cc_last_name,
		   credit.cc_first_name,
		   bal.bal_ctlnum, 
		   bal.bal_balance, 
		   bal.bal_fractional_cent, 
		   bal.class, 
		   bal.balance_type
	from
	(select
		rownum as ctrn,
		c.class,
		c.currency_code,
		cd.divisor,
		c.service_type,
		c.rechg_threshold
	 from debit.classtab c, 
		  debit.currency_def cd, 
		  pcc
	 where c.class = pcc.class
	  AND c.currency_code = cd.currency_code) ct
	full outer join
	(select
		rownum pinrn,
		PP.PIN,
		PP.CLASS,
		PP.CTLNUM,
		pp.STATE as PIN_STATE,
		pp.BALANCE,
		pp.FRACTIONAL_CENT
	from debit.partitioned_pintab pp, 
		 pcc
	where pp.ctlnum = pcc.ctlnum
	) pin on ct.ctrn = pin.pinrn
	full outer join
	(select
		rownum as subrn,
		si.LAST_NAME,
		si.FIRST_NAME,
		si.EMAIL_ADDRESS,
		coalesce(si.SUBSCRIBER_PLAN_RESTRICTED, 'N') as SUBSCRIBER_PLAN_RESTRICTED,
		si.UNIV_APP_ACT_DATE,
		si.rechg_threshold,
		si.rechg_amount
	from debit.subscriber_info si, 
		 pcc
	where si.ctlnum = pcc.ctlnum
	) sub on pin.pinrn = sub.subrn
	full outer join
	(select
		rownum as planrn,
		p.class_id, 
		coalesce(p.ratetab,-1) AS RATETAB, 
		s.plan_id, 
		p.name,
		TO_CHAR(FROM_TZ(CAST( s.expired AS TIMESTAMP ), 'America/New_York') at time zone 'UTC', 
                'YYYY-MM-DD"T"HH24:MI:SS"Z"') as SUBSCRIBER_PLAN_EXPIRED_UTC,
		UPPER(coalesce(s.AUTO_RENEW, 'N')) AS AUTO_RENEW, 
		coalesce(s.STATUS, 'N') AS STATUS,
		s.TRANSACTION_ID, 
		coalesce(p.UNITS,-1) AS UNITS, 
		coalesce(p.TYPE, 'U') AS TYPE, 
		p.price, 
		p.term, 
		UPPER(coalesce(p.high_usage_plan, 'N')) AS HIGH_USAGE_PLAN,
		p.num_of_dest
	   FROM debit.subscriber_plan s, debit.plan_info p, debit.plan_info pr, debit.plan_info po, pcc
	   WHERE s.ctlnum = pcc.ctlnum
		AND UPPER(coalesce(s.status, ' ')) = 'A'
		AND s.activated IS NOT NULL AND s.activated <= SYSDATE
		AND s.plan_id = p.plan_id
		AND ((s.expired IS NULL AND UPPER(coalesce(p.TYPE, 'U')) in ('D', 'M'))
			OR (s.expired IS NOT NULL AND s.expired > SYSDATE))
		AND p.replacement_plan_id = pr.plan_id (+)
		AND p.override_plan_id = po.plan_id (+)
	) plan on plan.planrn = sub.subrn
	full outer join
	(select
		rownum as topuprn,
		tt.TIMESTAMP
	from debit.topup_totals tt, 
		 pcc
	where tt.ctlnum = pcc.ctlnum
	) topup on plan.planrn = topup.topuprn
	full outer join
	(select
		rownum as creditrn,
		cci.CCARD_NUMBER,
		cci.CCARD_TYPE,
		cci.NAME_ON_CCARD,
		cci.CCARD_EXP_DATE,
		cci.CCARD_ADDRESS1,
		cci.CCARD_ADDRESS2,
		cci.CCARD_CITY,
		cci.CCARD_STATE,
		cci.CCARD_ZIP,
		cci.CCARD_COUNTRY,
		UPPER(coalesce(cci.ALLOW_MULTI_USE, 'N')) AS ALLOW_MULTI_USE,
		cci.CCARD_VAULT_HANDLE,
		cci.CC_LAST_NAME,
		cci.CC_FIRST_NAME
	from debit.credit_card_info cci, 
		 pcc
	where cci.ctlnum = pcc.ctlnum
	 AND coalesce(cci.CCARD_VAULT_HANDLE, -1) > 0
	 AND UPPER(coalesce(cci.CCARD_DISABLED, 'N')) <> 'Y'
	) credit on credit.creditrn = topup.topuprn
	full outer join
	(select
		rownum as balrn,
		PP.CTLNUM as BAL_CTLNUM,
		pp.BALANCE as BAL_BALANCE,
		pp.FRACTIONAL_CENT as BAL_FRACTIONAL_CENT,
		pp.CLASS,
		m.balance_type,
		m.call_type,
		m.status as bal_status
	 from debit.partitioned_pintab pp,
		debit.multi_bal_pin_map m, 
		pcc
	 where
		m.master_ctlnum = pcc.ctlnum
		and pp.ctlnum = m.balance_ctlnum
		and (pp.BALANCE_EXP_DATE IS NULL OR pp.BALANCE_EXP_DATE > SYSDATE)
	) bal on bal.balrn = credit.creditrn;`

**Comment by ivpoznyak** [comment]
Hello. We ran the test with DPI_DEBUG_LEVEL=92 and it didn't give more info. Adding results below. As we used pretty old GODROR version we updated to the latest but we have the same issue with it.
ODPI [00058] 2023-08-03 09:06:39.749: fn end dpiStmt_addRef(0x7fa2a83857d0) -> 0
{
    "app": "query-account-service",
    "file": "/src/oracle/log.go:37",
    "func": "github.com/coretech/query-account-service/oracle.logQueryFinish()",
    "gid": 315,
    "level": "debug",
    "msg": "oracle query finished, took 4.001s",
    "request_id": "2f5c5a80-d505-4f40-a0a1-4b8a83a31205",
    "terra_env": "qa",
    "time": "2023-08-03T09:06:39.749960935Z"
}
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiStmt_fetchRows(0x7fa2a83857d0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiStmt_fetchRows(0x7fa2a83857d0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiStmt_fetchRows(0x7fa2a83857d0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiStmt_fetchRows(0x7fa2a83857d0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2989381f0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2989381f0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa29893bef0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa29893bef0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa29893eb00)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa29893eb00) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa298942800)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa298942800) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa298945210)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa298945210) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa298948f10)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa298948f10) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa298957820)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa298957820) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa298966130)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa298966130) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa298969e30)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa298969e30) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa29896c840)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa29896c840) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa298970540)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa298970540) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa29897ee50)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa29897ee50) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa294a8cea0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa294a8cea0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa294a934e0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa294a934e0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2945dc5b0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2945dc5b0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a069b4f0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a069b4f0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a069e3f0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a069e3f0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a06a20f0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a06a20f0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a06a5df0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a06a5df0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a06a74c0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a06a74c0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a088b820)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a088b820) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a088f520)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a088f520) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a0895a30)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a0895a30) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08a4340)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08a4340) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08a6d50)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08a6d50) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08a9760)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08a9760) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08ad460)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08ad460) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08b1170)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08b1170) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08b3b80)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08b3b80) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08b6590)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08b6590) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08bb6a0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08bb6a0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08be5a0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08be5a0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08c5eb0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08c5eb0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08c88c0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08c88c0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08d51d0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08d51d0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08d84e0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08d84e0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08e75f0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08e75f0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a08f6700)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a08f6700) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a0903010)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a0903010) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a090f920)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a090f920) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a0912e30)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a0912e30) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a091cf40)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a091cf40) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a091f950)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a091f950) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a0923650)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a0923650) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a092af60)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a092af60) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a0932870)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a0932870) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a0941180)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a0941180) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a0944e80)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a0944e80) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a0953790)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a0953790) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a0957490)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a0957490) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiStmt_release(0x7fa2a83857d0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiStmt_release(0x7fa2a83857d0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a83843e0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a83843e0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a83844a0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a83844a0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a83845c0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a83845c0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a8384740)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a8384740) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiVar_release(0x7fa2a83848c0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiVar_release(0x7fa2a83848c0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiStmt_getInfo(0x7fa2a83857d0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiStmt_getInfo(0x7fa2a83857d0) -> 0
ODPI [00058] 2023-08-03 09:06:39.750: fn start dpiStmt_release(0x7fa2a83857d0)
ODPI [00058] 2023-08-03 09:06:39.750: fn end dpiStmt_release(0x7fa2a83857d0) -> 0
{
    "app": "query-account-service",
    "file": "/src/oracle/common.go:93",
    "func": "github.com/coretech/query-account-service/oracle.fillQueryAccountRecords()",
    "gid": 315,
    "level": "debug",
    "msg": "QueryAccountByAni:4136366462 found 1",
    "request_id": "2f5c5a80-d505-4f40-a0a1-4b8a83a31205",
    "terra_env": "qa",
    "time": "2023-08-03T09:06:39.750796312Z"
}
{
    "app": "query-account-service",
    "file": "/src/api/api.go:549",
    "func": "github.com/coretech/query-account-service/api.(*API).wrapper.func1()",
    "gid": 315,
    "level": "info",
    "msg": "finish processing request [GET] /account/US/ani/4136366462, took 6.083s",
    "request_id": "2f5c5a80-d505-4f40-a0a1-4b8a83a31205",
    "terra_env": "qa",
    "time": "2023-08-03T09:06:39.750990568Z"
}
ODPI [00058] 2023-08-03 09:06:39.751: fn start dpiStmt_getInfo(0x2c5b410)
ODPI [00058] 2023-08-03 09:06:39.751: fn end dpiStmt_getInfo(0x2c5b410) -> 0
ODPI [00058] 2023-08-03 09:06:39.751: fn start dpiStmt_getBindCount(0x2c5b410)
ODPI [00058] 2023-08-03 09:06:39.751: fn end dpiStmt_getBindCount(0x2c5b410) -> 0
ODPI [00058] 2023-08-03 09:06:39.751: fn start dpiConn_newVar(0x7fa2980adcc0)
ODPI [00058] 2023-08-03 09:06:39.751: fn end dpiConn_newVar(0x7fa2980adcc0) -> 0
ODPI [00058] 2023-08-03 09:06:39.751: fn start dpiVar_setFromBytes(0x7fa2a069b4f0)
ODPI [00058] 2023-08-03 09:06:39.751: fn end dpiVar_setFromBytes(0x7fa2a069b4f0) -> 0
ODPI [00058] 2023-08-03 09:06:39.751: fn start dpiStmt_bindByPos(0x2c5b410)
ODPI [00058] 2023-08-03 09:06:39.751: fn end dpiStmt_bindByPos(0x2c5b410) -> 0
ODPI [00058] 2023-08-03 09:06:39.751: fn start dpiConn_setCallTimeout(0x7fa2980adcc0)
ODPI [00058] 2023-08-03 09:06:39.751: fn end dpiConn_setCallTimeout(0x7fa2980adcc0) -> 0
ODPI [00058] 2023-08-03 09:06:39.751: fn start dpiStmt_execute(0x2c5b410)
fatal error: unexpected signal during runtime execution
ODPI [00032] 2023-08-03 09:06:39.754: fn end dpiStmt_fetchRows(0x7fa2b430eaf0) -> 0
ODPI [00060] 2023-08-03 09:06:39.754: fn end dpiStmt_fetchRows(0x7fa2a0060110) -> 0
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fa2d314072a]
runtime stack:
runtime.throw({0xc2d46b, 0x7fa29c25a4f8})
    /usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
    /usr/local/go/src/runtime/signal_unix.go:719 +0x389
goroutine 28729 [syscall]:
runtime.cgocall(0xab2c50, 0xc00099f6d0)
    /usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc00099f6a8 sp=0xc00099f670 pc=0x40fc3c
github.com/godror/godror._Cfunc_dpiStmt_execute(0x2c5b410, 0x20, 0xc000e9e978)
    _cgo_gotypes.go:4173 +0x4c fp=0xc00099f6d0 sp=0xc00099f6a8 pc=0x790d8c
github.com/godror/godror.(*statement).QueryContext.func2.1(0xc000fd5800, 0xd6a0e0, 0xc000fd5800)
    /src/vendor/github.com/godror/godror/stmt.go:555 +0x5c fp=0xc00099f718 sp=0xc00099f6d0 pc=0x7b5ddc
github.com/godror/godror.(*statement).QueryContext.func2()
    /src/vendor/github.com/godror/godror/stmt.go:555 +0x12f fp=0xc00099f7e0 sp=0xc00099f718 pc=0x7b5b6f
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00099f7e8 sp=0xc00099f7e0 pc=0x470e41
created by github.com/godror/godror.(*statement).QueryContext
    /src/vendor/github.com/godror/godror/stmt.go:546 +0x73d
goroutine 1 [semacquire, 7 minutes]:
sync.runtime_Semacquire(0x0)
    /usr/local/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc00010c480)
    /usr/local/go/src/sync/waitgroup.go:130 +0x71
main.main()
    /src/main.go:181 +0x2be

**Comment by tgulacsi** [comment]
This truncated log is unusable (I know it's truncated because it does not contain the query SQL).

    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fa2d314072a]

The addr=0x0 says that it is a NULL (nil) dereference.
But 

    github.com/godror/godror._Cfunc_dpiStmt_execute(0x2c5b410, 0x20, 0xc000e9e978)

does not contain NULL, so it must be some earlier prepared variable.
You still haven't showed us the program chunk (QueryContext call) you're using, with the arguments' and their types.

stmt.go line 555 does not contain dpiStmt_execute - which version are you trying ?

**Comment by ivpoznyak** [comment]
godror(0.13.2) go(1.12) after update we don't have craches with stackstrace but application getting stoped by receiving shutdown signal.
