### ISSUE TITLE
v0.19.2 _Cfunc_dpiStmt_release panic

### ISSUE THREAD

**Issue by travelliu** [godror/godror#86]
**Describe the bug**
go run ora.go
```
ora(28776,0x9d87dc0) malloc: Incorrect checksum for freed object 0x7605db8: probably modified after being freed.
Corrupt value: 0xffffffff00000000
ora(28776,0x9d87dc0) malloc: *** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff6b3ad33a m=0 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7fff6b3ad33a
stack: frame={sp:0x7ffeefbfede8, fp:0x0} stack=[0x7ffeefb80298,0x7ffeefbff300)
00007ffeefbfece8:  00007fff6b4407da  0000000000000000 
00007ffeefbfecf8:  00007ffeefbfed48  00007ffeefbfed40 
00007ffeefbfed08:  00000000043fc000  0000000009d87dc0 
00007ffeefbfed18:  00007ffeefbff5d4  00007fff6b440765 
00007ffeefbfed28:  0000000000000043  00007ffeefbfee10 
00007ffeefbfed38:  00007fff6b45cf24  0000003000000018 
00007ffeefbfed48:  00007ffeefbfee20  00007ffeefbfed60 
00007ffeefbfed58:  0000000000000000  0000000000000000 
00007ffeefbfed68:  0000000000000000  00007fff6b440765 
00007ffeefbfed78:  00000000043fc045  0000000000000000 
00007ffeefbfed88:  0000000000000000  00007fff6b43c8b0 
00007ffeefbfed98:  00007ffeefbfee08  00000000043fb028 
00007ffeefbfeda8:  0000000000000043  00007ffeefbfedd8 
00007ffeefbfedb8:  0000000000000043  00007ffeefbfedf0 
00007ffeefbfedc8:  00007fff6b3a891f  00007ffeefbfee10 
00007ffeefbfedd8:  00000000043fc000  00000000043fb000 
00007ffeefbfede8: <00007fff6b469e60  0000000000000003 
00007ffeefbfedf8:  00000000043fb028  00007ffeefbfee30 
00007ffeefbfee08:  0000000000000000  00007ffeefbfee50 
00007ffeefbfee18:  00007fff6b334808  00000000043fb028 
00007ffeefbfee28:  00007fff6b3a8399  00007ffffffff9df 
00007ffeefbfee38:  ffffffff043fb000  00000000043fb000 
00007ffeefbfee48:  0000000000000003  00007ffeefbfeeb0 
00007ffeefbfee58:  00007fff6b42a50b  0000000000000000 
00007ffeefbfee68:  0000000009d87dc0  00007ffeefbfef70 
00007ffeefbfee78:  0000000000000000  00007fff6b43d875 
00007ffeefbfee88:  00000000f0f0efee  0000000007605d00 
00007ffeefbfee98:  0000000007600000  00000000000000b0 
00007ffeefbfeea8:  0000000000000000  00007ffeefbfef90 
00007ffeefbfeeb8:  00007fff6b43bd27  0000000000000000 
00007ffeefbfeec8:  0000000000000000  0000000000000000 
00007ffeefbfeed8:  0000000007605db8  ffffffff00000000 
runtime: unknown pc 0x7fff6b3ad33a
stack: frame={sp:0x7ffeefbfede8, fp:0x0} stack=[0x7ffeefb80298,0x7ffeefbff300)
00007ffeefbfece8:  00007fff6b4407da  0000000000000000 
00007ffeefbfecf8:  00007ffeefbfed48  00007ffeefbfed40 
00007ffeefbfed08:  00000000043fc000  0000000009d87dc0 
00007ffeefbfed18:  00007ffeefbff5d4  00007fff6b440765 
00007ffeefbfed28:  0000000000000043  00007ffeefbfee10 
00007ffeefbfed38:  00007fff6b45cf24  0000003000000018 
00007ffeefbfed48:  00007ffeefbfee20  00007ffeefbfed60 
00007ffeefbfed58:  0000000000000000  0000000000000000 
00007ffeefbfed68:  0000000000000000  00007fff6b440765 
00007ffeefbfed78:  00000000043fc045  0000000000000000 
00007ffeefbfed88:  0000000000000000  00007fff6b43c8b0 
00007ffeefbfed98:  00007ffeefbfee08  00000000043fb028 
00007ffeefbfeda8:  0000000000000043  00007ffeefbfedd8 
00007ffeefbfedb8:  0000000000000043  00007ffeefbfedf0 
00007ffeefbfedc8:  00007fff6b3a891f  00007ffeefbfee10 
00007ffeefbfedd8:  00000000043fc000  00000000043fb000 
00007ffeefbfede8: <00007fff6b469e60  0000000000000003 
00007ffeefbfedf8:  00000000043fb028  00007ffeefbfee30 
00007ffeefbfee08:  0000000000000000  00007ffeefbfee50 
00007ffeefbfee18:  00007fff6b334808  00000000043fb028 
00007ffeefbfee28:  00007fff6b3a8399  00007ffffffff9df 
00007ffeefbfee38:  ffffffff043fb000  00000000043fb000 
00007ffeefbfee48:  0000000000000003  00007ffeefbfeeb0 
00007ffeefbfee58:  00007fff6b42a50b  0000000000000000 
00007ffeefbfee68:  0000000009d87dc0  00007ffeefbfef70 
00007ffeefbfee78:  0000000000000000  00007fff6b43d875 
00007ffeefbfee88:  00000000f0f0efee  0000000007605d00 
00007ffeefbfee98:  0000000007600000  00000000000000b0 
00007ffeefbfeea8:  0000000000000000  00007ffeefbfef90 
00007ffeefbfeeb8:  00007fff6b43bd27  0000000000000000 
00007ffeefbfeec8:  0000000000000000  0000000000000000 
00007ffeefbfeed8:  0000000007605db8  ffffffff00000000 

goroutine 1 [syscall]:
runtime.cgocall(0x4162520, 0xc0000e7a30, 0xc0000e7a38)
        /usr/local/Cellar/go@1.13/1.13.11/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc0000e7a00 sp=0xc0000e79c8 pc=0x4004a5b
github.com/godror/godror._Cfunc_dpiStmt_release(0x44070f0, 0x0)
        _cgo_gotypes.go:4412 +0x49 fp=0xc0000e7a30 sp=0xc0000e7a00 pc=0x40e7499
github.com/godror/godror.(*statement).closeNotLocking.func2(0x44070f0, 0x41bbc60)
        /Users/travel/Documents/Code/go/pkg/mod/github.com/godror/godror@v0.19.2/stmt.go:295 +0x56 fp=0xc0000e7a68 sp=0xc0000e7a30 pc=0x4115da6
github.com/godror/godror.(*statement).closeNotLocking(0xc00010d040, 0xc0000701e0, 0x41eede0)
        /Users/travel/Documents/Code/go/pkg/mod/github.com/godror/godror@v0.19.2/stmt.go:295 +0x1f7 fp=0xc0000e7b00 sp=0xc0000e7a68 pc=0x40fc6a7
github.com/godror/godror.(*statement).Close(0xc00010d040, 0x0, 0x0)
        /Users/travel/Documents/Code/go/pkg/mod/github.com/godror/godror@v0.19.2/stmt.go:267 +0x8d fp=0xc0000e7b68 sp=0xc0000e7b00 pc=0x40fc43d
database/sql.(*driverStmt).Close(0xc0000fa680, 0x0, 0x0)
        /usr/local/Cellar/go@1.13/1.13.11/libexec/src/database/sql/sql.go:605 +0x9a fp=0xc0000e7bc8 sp=0xc0000e7b68 pc=0x40b891a
database/sql.(*Rows).close(0xc000116080, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go@1.13/1.13.11/libexec/src/database/sql/sql.go:3086 +0x1af fp=0xc0000e7c50 sp=0xc0000e7bc8 pc=0x40be5ff
database/sql.(*Rows).Close(...)
        /usr/local/Cellar/go@1.13/1.13.11/libexec/src/database/sql/sql.go:3059
database/sql.(*Rows).Next(0xc000116080, 0xc0000e7e60)
        /usr/local/Cellar/go@1.13/1.13.11/libexec/src/database/sql/sql.go:2748 +0xb8 fp=0xc0000e7cb0 sp=0xc0000e7c50 pc=0x40bda08
main.main()
        /Users/travel/Documents/Code/go/src/gitlab.enmotech.com/cloudassistant/mtk/v2/cmd/ora.go:45 +0x579 fp=0xc0000e7f60 sp=0xc0000e7cb0 pc=0x4121ba9
runtime.main()
        /usr/local/Cellar/go@1.13/1.13.11/libexec/src/runtime/proc.go:203 +0x21e fp=0xc0000e7fe0 sp=0xc0000e7f60 pc=0x402eefe
runtime.goexit()
        /usr/local/Cellar/go@1.13/1.13.11/libexec/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000e7fe8 sp=0xc0000e7fe0 pc=0x4059061

goroutine 6 [select]:
database/sql.(*DB).connectionOpener(0xc0000ba000, 0x41eff60, 0xc0000280c0)
        /usr/local/Cellar/go@1.13/1.13.11/libexec/src/database/sql/sql.go:1052 +0xe8
created by database/sql.OpenDB
        /usr/local/Cellar/go@1.13/1.13.11/libexec/src/database/sql/sql.go:722 +0x15d

goroutine 7 [select]:
database/sql.(*DB).connectionResetter(0xc0000ba000, 0x41eff60, 0xc0000280c0)
        /usr/local/Cellar/go@1.13/1.13.11/libexec/src/database/sql/sql.go:1065 +0xfb
created by database/sql.OpenDB
        /usr/local/Cellar/go@1.13/1.13.11/libexec/src/database/sql/sql.go:723 +0x193

goroutine 33 [semacquire]:
sync.runtime_SemacquireMutex(0xc0001160b4, 0x0, 0x1)

```

**To Reproduce**
```
package main

import (
	"context"
	"database/sql"
	"github.com/godror/godror"
	"github.com/pkg/errors"
	"log"
	"time"
)

func testContext(name string) context.Context {
	return godror.ContextWithTraceTag(context.Background(), godror.TraceTag{Module: "Test" + name})
}
func main() {
	dsn := "user=system password=oracle connectString=\"(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.56.65)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=orcl)))\"\nconfigDir= connectionClass=godror enableEvents=0 heterogeneousPool=0 libDir=\nnewPassword= poolIncrement=0 poolMaxSessions=0 poolMinSessions=0 poolSessionMaxLifetime=0s\npoolSessionTimeout=0s poolWaitTimeout=0s prelim=0 standaloneConnection=0 sysasm=0\nsysdba=0 sysoper=0 timezone=local"
	testDb, err := sql.Open("godror", dsn)
	if err != nil {
		log.Println(err)
		return
	}
	ctx, cancel := context.WithTimeout(testContext("ROWID"), 10*time.Second)
	defer cancel()
	
	const tbl = "test_rowid_t"
	testDb.ExecContext(ctx, "DROP TABLE "+tbl)
	qry := "CREATE TABLE " + tbl + " (F_seq NUMBER(6))"
	if _, err := testDb.ExecContext(ctx, qry); err != nil {
		log.Fatal(errors.Errorf("%s: %w", qry, err))
	}
	defer func() { testDb.ExecContext(testContext("ROWID-drop"), "DROP TABLE "+tbl) }()
	
	qry = "INSERT INTO " + tbl + " (F_seq) VALUES (:1)"
	for i := 0; i < 10; i++ {
		if _, err := testDb.ExecContext(ctx, qry, i); err != nil {
			log.Fatal(errors.Errorf("%s: %w", qry, err))
		}
	}
	qry = "SELECT F_seq, ROWID FROM " + tbl + " ORDER BY F_seq"
	rows, err := testDb.QueryContext(ctx, qry)
	if err != nil {
		log.Fatal(errors.Errorf("%s: %w", qry, err))
	}
	defer rows.Close()
	for rows.Next() {
		var i int
		var rowid string
		if err = rows.Scan(&i, &rowid); err != nil {
			log.Fatalf("scan: %+v", err)
		}
		if len(rowid) != 18 {
			log.Printf("%d. got %v (%d bytes), wanted sth 18 bytes", i, rowid, len(rowid))
		}
	}
	if err = rows.Err(); err != nil {
		log.Fatal(err)
	}
}

```

**Your oracle client version**
11.2.0.4.0

**Your godror version**
v0.19.2

**Your go version**
1.13.0

**Your gcc version**
Apple clang version 11.0.3 (clang-1103.0.32.62)

**Machine (please complete the following information):**
 - OS: MacOS
 - Architecture:
 - Version: 10.15

**Additional context**

**Comment by tgulacsi** [comment]
I don't see obvious problems.
How reliable is this panic?
I cannot reproduce it with Go 1.15 - nether using standalone connections, nor with pooled.
I've tried to mitigate it in @master but I don't know how effective it is.

**Comment by cjbj** [comment]
A couple of comments:
- it reproduces for me on macOS with 0.19.3 but not with 0.19.1.  I was using Go 1.14.6, Oracle Instant Client 19.3
- Unless you need to connect to Oracle DB older than 11.2, you should upgrade your Oracle Instant Client to 19c.  This will connect to Oracle DB 11.2 onwards.  In your `Open()`, use `libDir=/Users/whatever/instantclient_19_3` in the dsn.
- your long connect string is identical to the shorter form `"192.168.56.65/orcl"`

**Comment by tgulacsi** [comment]
@cjbj strange - see `git diff v0.19.1 *.go` - ony the rowid handling has been added in rows.go.
Maybe my use of `dpiRowid_release(cRowid)` is wrong? What if you comment that out?

**Comment by travelliu** [comment]
runs normally after comment dpiRowid_release(cRowid)
